services:
  web:
    build: 
      context: .. #portfolio
      args: #variables en dockerfile para la construcción de la
        - USUARIO=diego
      dockerfile: ./deploy/Dockerfile
    image: dmorrid/ubbase
    container_name: proyecto_react
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      - netcaronte:
        ipv4_address: $(IP)
networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: $(SUBNET) 