services:
  web:
    build: 
      context: .. #portfolio
      args:
        - USUARIO=diego
      dockerfile: ./dockerfile
    image: dmorrid/ubbase
    container_name: ctportfolio
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      - netcaronte:
        ipv4_address: $(IP)
    ports:
      -"${PORT_Web}:80"
networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: $(SUBNET) 
args:
  - Proyecto=$(Proyecto)
  - USUARIO=${USUARIO}
  - TIPO=$(TIPO)
env_file:
  - ./.env